In [1]:
import pandas as pd

# Load the processed electricity price dataset
test_df = pd.read_csv('test_processed.csv')

# Load the gas price dataset
gas_df = pd.read_csv('gas_2024.csv')  # Replace with the actual file path
gas_df = gas_df.rename(columns={"Day": "date", "Gas (NCG, THE)": "gas_price"})

# Convert the 'date' column in gas data to datetime format
gas_df['date'] = pd.to_datetime(gas_df['date'], format='%d.%m.%Y')

# Create a temporary date column in test DataFrame for merging
test_df['date'] = pd.to_datetime(test_df['ds']).dt.date  # Extract only the date from the 'ds' column
test_df['date'] = pd.to_datetime(test_df['date'])  # Ensure it is a datetime64[ns] type

In [2]:
gas_df.head()

        date  gas_price
0 2024-01-01     31.574
1 2024-01-02     31.634
2 2024-01-03     30.392
3 2024-01-04     31.780
4 2024-01-05     33.168

In [3]:
test_df.head()

                    ds     y           unique_id       date
0  2024-01-01 00:00:00  0.10  electricity_prices 2024-01-01
1  2024-01-01 01:00:00  0.01  electricity_prices 2024-01-01
2  2024-01-01 02:00:00  0.00  electricity_prices 2024-01-01
3  2024-01-01 03:00:00 -0.01  electricity_prices 2024-01-01
4  2024-01-01 04:00:00 -0.03  electricity_prices 2024-01-01

In [4]:
# Merge gas prices into the electricity dataset using the temporary 'date' column
test_df = pd.merge(test_df, gas_df, how='left', left_on='date', right_on='date')

# Drop the temporary 'date' column (it was only used for merging)
test_df = test_df.drop(columns=['date'])

# Save the updated dataset to a new CSV file
test_df.to_csv('test_with_gas.csv', index=False)

print("Gas prices successfully added to test dataset.")

Gas prices successfully added to test dataset.